# Generated by Django 4.0.5 on 2022-07-08 19:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_info', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_saved', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField()),
                ('comment', models.CharField(max_length=300, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calculator.customer')),
                ('user', models.ForeignKey(auto_created=True, blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('Transport', 'Transport'), ('Concrete', 'Concrete'), ('Rental', 'Rental'), ('Paving', 'Paving'), ('Chipping', 'Chipping'), ('Other', 'Other')], default='Other', max_length=15)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('unit', models.CharField(choices=[('n/a', 'n/a'), ('m2', 'm2'), ('t', 't'), ('h', 'h'), ('km', 'km'), ('m3', 'm3'), ('Item', 'Item')], default='n/a', max_length=15)),
                ('comment', models.CharField(blank=True, max_length=250, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, default=1)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calculator.service')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calculator.quote')),
            ],
        ),
    ]
