# Generated by Django 4.0.5 on 2022-07-02 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='digital',
        ),
    ]
