# Generated by Django 4.0.5 on 2022-07-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_alter_customer_customer_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='comment',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
