# Generated by Django 4.0.5 on 2022-07-08 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_alter_quote_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='price',
            new_name='priceEUR',
        ),
        migrations.RemoveField(
            model_name='service',
            name='slug',
        ),
        migrations.AlterField(
            model_name='quote',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.customer'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.service'),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.quote'),
        ),
    ]
