# Generated by Django 4.0.5 on 2022-07-02 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_alter_service_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='group',
            field=models.CharField(choices=[('Transport', 'Transport'), ('Concrete', 'Concrete'), ('Rental', 'Rental'), ('Paving', 'Paving'), ('Chipping', 'Chipping')], default='n/a', max_length=15),
        ),
    ]
