# Generated by Django 4.0.5 on 2022-07-02 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_alter_service_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='group',
            field=models.CharField(choices=[('Transport', 'Transport'), ('Concrete', 'Concrete'), ('Rental', 'Rental'), ('Paving', 'Paving'), ('Chipping', 'Chipping'), ('Other', 'Other')], default='n/a', max_length=15),
        ),
    ]
