# Generated by Django 4.0.5 on 2022-07-02 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_alter_service_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='transaction_id',
            new_name='doc_id',
        ),
        migrations.RemoveField(
            model_name='document',
            name='complete',
        ),
    ]
