# Generated by Django 4.0.5 on 2022-07-03 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0007_rename_transaction_id_document_doc_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='customer_name',
            new_name='customer',
        ),
    ]
