# Generated by Django 4.0.5 on 2022-07-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0008_rename_customer_name_document_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='comment',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
