# Generated by Django 4.0.5 on 2022-07-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0010_rename_name_employee_user_remove_document_doc_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(default='Karen', max_length=30),
        ),
    ]
