# Generated by Django 4.0.5 on 2022-07-05 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0012_rename_created_by_document_employee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='Quote',
        ),
        migrations.RenameModel(
            old_name='DocumentItem',
            new_name='QuoteItem',
        ),
    ]
