# Generated by Django 4.0.5 on 2022-07-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0013_rename_document_quote_rename_documentitem_quoteitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=20),
        ),
    ]
